server:
  port: 8081

logging:
  level:
    com:
      best: debug
#data:
#  url:192.168.174.133
#  url:8.130.19.39
#  url:8.130.98.16 - elasticsearch -   data:elasticsearch
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.174.133:8066/db1?characterEncoding=utf-8&autoReconnect=true&useSSL=no
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#  redis:
#    host: 192.168.174.133
#    port: 6379
#    password: 123456
#    database: 0
#    timeout: 5000
#  rabbitmq:
#    host: 192.168.174.133
#    port: 5672
#    username: guest
#    password: guest
#  elasticsearch:
#    rest:
#      uris: http://192.168.174.133:9200
#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      client:
#        reactive:
#          endpoints: 192.168.174.133:9200
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB
#  resources:
#    static-locations: file:/webpage/wechatfile/

spring:
      datasource: # 数据库配置
        url: jdbc:mysql://8.130.19.39:8066/db1?characterEncoding=utf-8&autoReconnect=true&useSSL=no
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        hikari:
          max-lifetime: 120000
      redis: # redis配置
        host: 8.130.19.39
        port: 6379
        password: 123456
        database: 1
        timeout: 5000
      rabbitmq: # rabbitmq配置
        host: 8.130.19.39
        port: 5672
        username: admin
        password: 123456
      elasticsearch:
        rest:
          uris: http://8.130.98.16:9200
      data:
        elasticsearch:
          repositories:
            enabled: true
          client:
            reactive:
              endpoints: 8.130.98.16:9200
      servlet:
        multipart:
          max-file-size: 20MB # 上传文件大小限制
          max-request-size: 20MB
      resources:
        static-locations: file:/webpage/wechatfile/ # 本地文件路径

